//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountProduct
    {
        public int DiscountProductID { get; set; }
        public int DiscountProgramID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> QuantityDiscounted { get; set; }
    
        public virtual DiscountProgram DiscountProgram { get; set; }
        public virtual Product Product { get; set; }
    }
}
