//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPicture
    {
        public int ProductPictureID { get; set; }
        public int ProductID { get; set; }
        public string URLPicture { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
